# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Song.delete_all
PlaylistSong.delete_all
Playlist.delete_all
Artist.delete_all
Album.delete_all


user1 = User.create(username: "snowball", email: "snowball@snowball.cute", password: "snowball")
a = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/users/snowball.jpg')
user1.avatar.attach(io: a, filename: 'snowball.jpg')
b = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/users/snowball.jpg')
user2 = User.create(username: "snoop dogg", email: "snoop@lion.rasta", password: "snoopy")
user2.avatar.attach(io: b, filename: 'snowball.jpg')


artist1 = Artist.create(name: 'Asthmatic Astronaut', bio: "The wheezy space man")
artist1.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist1.jpg'), filename: 'pic.jpg')
album1a = Album.create(title: 'Exposing All Emotions', year: 2012, genre: "Hip Hop", artist_id: artist1.id)
album1a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_Exposing_All_Emotions_-_20120815102617148.jpg'), filename: 'cover.jpg')
song1a1 = Song.create(title: "A New Tone", duration: 211, album_id: album1a.id)
song1a2 = Song.create(title: "Body Language", duration: 247, album_id: album1a.id)
song1a3 = Song.create(title: "And Still They Come A Creeping", duration: 276, album_id: album1a.id)
song1a4 = Song.create(title: "Something To Work On", duration: 296, album_id: album1a.id)
song1a5 = Song.create(title: "After Party", duration: 175, album_id: album1a.id)
song1a6 = Song.create(title: "Run The Tape", duration: 226, album_id: album1a.id)
song1a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_01_-_A_New_Tone_ft_dsoul_soul_samurai.mp3'), filename: 'audio.mp3')
song1a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_02_-_Body_Language.mp3'), filename: 'audio.mp3')
song1a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_03_-_And_Still_They_Come_A_Creeping.mp3'), filename: 'audio.mp3')
song1a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_04_-_Something_To_Work_On.mp3'), filename: 'audio.mp3')
song1a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_05_-_After_Party.mp3'), filename: 'audio.mp3')
song1a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Asthmatic_Astronaut_-_Exposing_All_Emotions/Asthmatic_Astronaut_-_06_-_Run_The_Tape.mp3'), filename: 'audio.mp3')


artist2 = Artist.create(name: 'Black Ant')
artist2.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist2.jpg'), filename: 'pic.jpg')
album2a = Album.create(title: 'Free Beats Sel. 3', year: 2010, genre: "Hip Hop", artist_id: artist2.id)
album2a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_Free_Beats_Sel_3_-_20100125165648429.jpg'), filename: 'cover.jpg')
song2a1 = Song.create(title: "Fater Lee", duration: 143, album_id: album2a.id)
song2a2 = Song.create(title: "Oh K.", duration: 83, album_id: album2a.id)
song2a3 = Song.create(title: "8bit2 3", duration: 38, album_id: album2a.id)
song2a4 = Song.create(title: "Black Ant", duration: 163, album_id: album2a.id)
song2a5 = Song.create(title: "Self Explainitory", duration: 150, album_id: album2a.id)
song2a6 = Song.create(title: "fACEMELETERmp3", duration: 128, album_id: album2a.id)
song2a7 = Song.create(title: "Boomerang", duration: 141, album_id: album2a.id)
song2a8 = Song.create(title: "Michael Vendette", duration: 143, album_id: album2a.id)
song2a9 = Song.create(title: "Christmas Eve 2009", duration: 83, album_id: album2a.id)
song2a10 = Song.create(title: "5 Piece", duration: 89, album_id: album2a.id)
song2a11 = Song.create(title: "government funded weed", duration: 105, album_id: album2a.id)
song2a12 = Song.create(title: "6,49", duration: 123, album_id: album2a.id)
song2a13 = Song.create(title: "1982", duration: 123, album_id: album2a.id)
song2a14 = Song.create(title: "Underdog", duration: 142, album_id: album2a.id)
song2a15 = Song.create(title: "D8M3", duration: 125, album_id: album2a.id)
song2a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_01_-_Fater_Lee.mp3'), filename: 'audio.mp3')
song2a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_02_-_Oh_K.mp3'), filename: 'audio.mp3')
song2a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_03_-_8bit2_3.mp3'), filename: 'audio.mp3')
song2a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_04_-_Black_Ant.mp3'), filename: 'audio.mp3')
song2a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_05_-_Self_Explainitory.mp3'), filename: 'audio.mp3')
song2a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_06_-_fACEMELTERmp3.mp3'), filename: 'audio.mp3')
song2a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_07_-_Boomerang.mp3'), filename: 'audio.mp3')
song2a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_08_-_Michael_Vendette.mp3'), filename: 'audio.mp3')
song2a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_09_-_Christmas_Eve_2009.mp3'), filename: 'audio.mp3')
song2a10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_10_-_5_Piece.mp3'), filename: 'audio.mp3')
song2a11.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_11_-_government_funded_weed.mp3'), filename: 'audio.mp3')
song2a12.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_12_-_649.mp3'), filename: 'audio.mp3')
song2a13.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_13_-_1982.mp3'), filename: 'audio.mp3')
song2a14.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_14_-_Underdog.mp3'), filename: 'audio.mp3')
song2a15.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Black_Ant_-_Free_Beats_Sel_3/Black_Ant_-_15_-_D8M3.mp3'), filename: 'audio.mp3')


artist3 = Artist.create(name: 'Blank & Kytt')
artist3.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist3.jpg'), filename: 'pic.jpg')
album3a = Album.create(title: 'Heavy, Crazy, Serious', year: 2012, genre: "Hip Hop", artist_id: artist3.id)
album3a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_Heavy_Crazy_Serious_-_20120510124341734.png'), filename: 'cover.png')
song3a1 = Song.create(title: "Thursday & Snow (Reprise)", duration: 116, album_id: album3a.id)
song3a2 = Song.create(title: "Jangle", duration: 115, album_id: album3a.id)
song3a3 = Song.create(title: "Cassette Thing", duration: 72, album_id: album3a.id)
song3a4 = Song.create(title: "Come Get Some", duration: 66, album_id: album3a.id)
song3a5 = Song.create(title: "Rock", duration: 65, album_id: album3a.id)
song3a6 = Song.create(title: "Deniro", duration: 92, album_id: album3a.id)
song3a7 = Song.create(title: "Flava", duration: 62, album_id: album3a.id)
song3a8 = Song.create(title: "RSPAN", duration: 51, album_id: album3a.id)
song3a9 = Song.create(title: "Sgt Frog", duration: 52, album_id: album3a.id)
song3a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_01_-_Thursday__Snow_Reprise.mp3'), filename: 'audio.mp3')
song3a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_02_-_Jangle.mp3'), filename: 'audio.mp3')
song3a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_03_-_Cassette_Thing.mp3'), filename: 'audio.mp3')
song3a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_04_-_Come_Get_Some.mp3'), filename: 'audio.mp3')
song3a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_05_-_Rock.mp3'), filename: 'audio.mp3')
song3a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_06_-_Deniro.mp3'), filename: 'audio.mp3')
song3a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_07_-_Flava.mp3'), filename: 'audio.mp3')
song3a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_08_-_RSPN.mp3'), filename: 'audio.mp3')
song3a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Blank__Kytt_-_Heavy_Crazy_Serious/Blank__Kytt_-_09_-_Sgt_Frog.mp3'), filename: 'audio.mp3')


artist4 = Artist.create(name: 'Broke For Free')
artist4.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist4.jpg'), filename: 'pic.jpg')
album4a = Album.create(title: 'Layers', year: 2012, genre: "Hip Hop", artist_id: artist4.id)
album4a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_Layers_-_20120418184903300.jpg'), filename: 'cover.jpg')
song4a1 = Song.create(title: "As Colorful As Ever", duration: 234, album_id: album4a.id)
song4a2 = Song.create(title: "Knock Knock", duration: 156, album_id: album4a.id)
song4a3 = Song.create(title: "Only Knows", duration: 179, album_id: album4a.id)
song4a4 = Song.create(title: "If", duration: 200, album_id: album4a.id)
song4a5 = Song.create(title: "Note Drop", duration: 190, album_id: album4a.id)
song4a6 = Song.create(title: "Murmur", duration: 248, album_id: album4a.id)
song4a7 = Song.create(title: "Spellbound", duration: 174, album_id: album4a.id)
song4a8 = Song.create(title: "The Collector", duration: 134, album_id: album4a.id)
song4a9 = Song.create(title: "Quit Bitching", duration: 244, album_id: album4a.id)
song4a10 = Song.create(title: "A Year", duration: 194, album_id: album4a.id)
song4a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_01_-_As_Colorful_As_Ever.mp3'), filename: 'audio.mp3')
song4a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_02_-_Knock_Knock.mp3'), filename: 'audio.mp3')
song4a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_03_-_Only_Knows.mp3'), filename: 'audio.mp3')
song4a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_04_-_If.mp3'), filename: 'audio.mp3')
song4a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_05_-_Note_Drop.mp3'), filename: 'audio.mp3')
song4a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_06_-_Murmur.mp3'), filename: 'audio.mp3')
song4a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_07_-_Spellbound.mp3'), filename: 'audio.mp3')
song4a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_08_-_The_Collector.mp3'), filename: 'audio.mp3')
song4a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_09_-_Quit_Bitching.mp3'), filename: 'audio.mp3')
song4a10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Layers/Broke_For_Free_-_10_-_A_Year.mp3'), filename: 'audio.mp3')

album4b = Album.create(title: 'Something EP', year: 2011, genre: "Hip Hop", artist_id: artist4.id)
album4b.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Something_EP/Broke_For_Free_-_Something_EP_-_20110708115706855.jpg'), filename: 'cover.jpg')
song4b1 = Song.create(title: "Something Jah", duration: 172, album_id: album4b.id)
song4b2 = Song.create(title: "Something Old", duration: 179, album_id: album4b.id)
song4b3 = Song.create(title: "Something Wobbly", duration: 225, album_id: album4b.id)
song4b4 = Song.create(title: "Something Galactic", duration: 270, album_id: album4b.id)
song4b5 = Song.create(title: "Something Elated", duration: 234, album_id: album4b.id)
song4a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Something_EP/Broke_For_Free_-_01_-_Something_Jah.mp3'), filename: 'audio.mp3')
song4a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Something_EP/Broke_For_Free_-_02_-_Something_Old.mp3'), filename: 'audio.mp3')
song4a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Something_EP/Broke_For_Free_-_03_-_Something_Wobbly.mp3'), filename: 'audio.mp3')
song4a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Something_EP/Broke_For_Free_-_04_-_Something_Galactic.mp3'), filename: 'audio.mp3')
song4a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Broke_For_Free_-_Something_EP/Broke_For_Free_-_05_-_Something_Elated.mp3'), filename: 'audio.mp3')


artist5 = Artist.create(name: 'Hogan Grip',
  bio: "Hogan Grip (DeclanQKelly and Tony Higgins aka junior85) is a duo born in a charity shop in the westside of Galway city on a warm June afternoon, in which was found an old, yellowing copy of Ben Hogan's seminal instructional golf book “Power Golf”. Inspired first by the exquisite line drawings and evocative chapter names and later (upon closer examination of the book's actual text) by Hogan's avuncular, firm-but-fair teaching technique and his touching dedication to a friend (Henry Picard) in the opening chapter, the band Hogan Grip came to fruition.")
artist5.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist5.jpg'), filename: 'pic.jpg')
album5a = Album.create(title: 'Stance Gives You Balance', year: 2010, genre: "Hip Hop", artist_id: artist5.id)
album5a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/junior85_-_Hogan_Grip_-_Stance_Gives_You_Balance_-_20100821193724436.jpg'), filename: 'cover.jpg')
song5a1 = Song.create(title: "Stance Gives You Power", duration: 225, album_id: album5a.id)
song5a2 = Song.create(title: "Interlude - Starting The Club Down", duration: 15, album_id: album5a.id)
song5a3 = Song.create(title: "Stance Gives You Balance", duration: 331, album_id: album5a.id)
song5a4 = Song.create(title: "Interlude - 'Reading The Greens'", duration: 40, album_id: album5a.id)
song5a5 = Song.create(title: "Iron Shots (For Accuracy)", duration: 427, album_id: album5a.id)
song5a6 = Song.create(title: "Interlude - 'Diagonal Stance'", duration: 45, album_id: album5a.id)
song5a7 = Song.create(title: "To Henry Picard - An Outstanding Teacher, An Outstanding Player And An Outstanding Man", duration: 125, album_id: album5a.id)
song5a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_01_-_Stance_Gives_You_Power.mp3'), filename: 'audio.mp3')
song5a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_02_-_Interlude_-_Starting_The_Club_Downmp3.mp3'), filename: 'audio.mp3')
song5a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_03_-_Stance_Gives_You_Balance.mp3'), filename: 'audio.mp3')
song5a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_04_-_Interlude_-_Reading_The_Greens.mp3'), filename: 'audio.mp3')
song5a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_05_-_Iron_Shots_For_Accuracy.mp3'), filename: 'audio.mp3')
song5a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_06_-_Interlude_-_Diagonal_Stance.mp3'), filename: 'audio.mp3')
song5a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/hip+hop/Hogan_Grip_-_Hogan_Grip_-_Stance_Gives_You_Balance/Hogan_Grip_-_07_-_To_Henry_Picard_-_An_Outstanding_Teacher_An_Oustanding_Player_And_An_Outstanding_Man.mp3'), filename: 'audio.mp3')


artist6 = Artist.create(name: 'Jahzzar')
artist6.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist6.jpg'), filename: 'pic.jpg')
album6a = Album.create(title: 'Smoke Factory', year: 2012, genre: "Indie Rock", artist_id: artist6.id)
album6a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_Smoke_Factory_-_20120326162411609.jpg'), filename: 'cover.jpg')
song6a1 = Song.create(title: "The last ones", duration: 180, album_id: album6a.id)
song6a2 = Song.create(title: "Brighter", duration: 252, album_id: album6a.id)
song6a3 = Song.create(title: "I need", duration: 166, album_id: album6a.id)
song6a4 = Song.create(title: "Look inside", duration: 223, album_id: album6a.id)
song6a5 = Song.create(title: "Origin", duration: 229, album_id: album6a.id)
song6a6 = Song.create(title: "Circles", duration: 336, album_id: album6a.id)
song6a7 = Song.create(title: "Anniversary", duration: 276, album_id: album6a.id)
song6a8 = Song.create(title: "Pause", duration: 225, album_id: album6a.id)
song6a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_01_-_The_last_ones.mp3'), filename: 'audio.mp3')
song6a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_02_-_Brighter.mp3'), filename: 'audio.mp3')
song6a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_03_-_I_need.mp3'), filename: 'audio.mp3')
song6a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_04_-_Look_inside.mp3'), filename: 'audio.mp3')
song6a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_05_-_Origin.mp3'), filename: 'audio.mp3')
song6a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_06_-_Circles.mp3'), filename: 'audio.mp3')
song6a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_07_-_Anniversary.mp3'), filename: 'audio.mp3')
song6a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Smoke_Factory/Jahzzar_-_08_-_Pause.mp3'), filename: 'audio.mp3')

album6b = Album.create(title: "Traveler's Guide", year: 2012, genre: "Indie Rock", artist_id: artist6.id)
album6b.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_Travellers_Guide_-_20120326162547357.jpg'), filename: 'cover.jpg')
song6b1 = Song.create(title: "Out of School", duration: 215, album_id: album6b.id)
song6b2 = Song.create(title: "FM", duration: 195, album_id: album6b.id)
song6b3 = Song.create(title: "Fireworks", duration: 229, album_id: album6b.id)
song6b4 = Song.create(title: "Storyteller", duration: 304, album_id: album6b.id)
song6b5 = Song.create(title: "Siesta", duration: 139, album_id: album6b.id)
song6b6 = Song.create(title: "Echoes", duration: 199, album_id: album6b.id)
song6b7 = Song.create(title: "Summercase", duration: 226, album_id: album6b.id)
song6b8 = Song.create(title: "Overdose", duration: 256, album_id: album6b.id)
song6b9 = Song.create(title: "So Easy", duration: 138, album_id: album6b.id)
song6b10 = Song.create(title: "April from the train", duration: 186, album_id: album6b.id)
song6b11 = Song.create(title: "Riots", duration: 172, album_id: album6b.id)
song6b12 = Song.create(title: "B-Side", duration: 207, album_id: album6b.id)
song6b13 = Song.create(title: "Italia 90", duration: 222, album_id: album6b.id)
song6b14 = Song.create(title: "Before & After", duration: 264, album_id: album6b.id)
song6b1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_01_-_Out_of_School.mp3'), filename: 'audio.mp3')
song6b2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_02_-_FM.mp3'), filename: 'audio.mp3')
song6b3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_03_-_Fireworks.mp3'), filename: 'audio.mp3')
song6b4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_04_-_Storyteller.mp3'), filename: 'audio.mp3')
song6b5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_05_-_Siesta.mp3'), filename: 'audio.mp3')
song6b6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_06_-_Echoes.mp3'), filename: 'audio.mp3')
song6b7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_07_-_Summercase.mp3'), filename: 'audio.mp3')
song6b8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_08_-_Overdose.mp3'), filename: 'audio.mp3')
song6b9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_09_-_So_Easy.mp3'), filename: 'audio.mp3')
song6b10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_10_-_April_from_the_train.mp3'), filename: 'audio.mp3')
song6b11.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_11_-_Riots.mp3'), filename: 'audio.mp3')
song6b12.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_12_-_B-Side.mp3'), filename: 'audio.mp3')
song6b13.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_13_-_Italia_90.mp3'), filename: 'audio.mp3')
song6b14.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Jahzzar_-_Travellers_Guide/Jahzzar_-_14_-_Before__After.mp3'), filename: 'audio.mp3')


artist7 = Artist.create(name: 'Scott Holmes')
artist7.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist7.jpg'), filename: 'pic.jpg')
album7a = Album.create(title: 'Corporate & Motivational Music', year: 2017, genre: "Indie Rock", artist_id: artist7.id)
album7a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_Corporate__Motivational_Music_-_2017030692053365.png'), filename: 'cover.jpg')
song7a1 = Song.create(title: "Corporate Success", duration: 226, album_id: album7a.id)
song7a2 = Song.create(title: "Corporate Initiative", duration: 214, album_id: album7a.id)
song7a3 = Song.create(title: "Corporate Presentation", duration: 246, album_id: album7a.id)
song7a4 = Song.create(title: "Corporate Uplifting", duration: 111, album_id: album7a.id)
song7a5 = Song.create(title: "Corporate Software", duration: 226, album_id: album7a.id)
song7a6 = Song.create(title: "Corporate Advertisement", duration: 174, album_id: album7a.id)
song7a7 = Song.create(title: "Corporate Technology", duration: 138, album_id: album7a.id)
song7a8 = Song.create(title: "Corporate Business", duration: 117, album_id: album7a.id)
song7a9 = Song.create(title: "Corporate Vision", duration: 157, album_id: album7a.id)
song7a10 = Song.create(title: "Inspiring Corporate", duration: 148, album_id: album7a.id)
song7a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_01_-_Corporate_Success.mp3'), filename: 'audio.mp3')
song7a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_02_-_Corporate_Innovative.mp3'), filename: 'audio.mp3')
song7a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_03_-_Corporate_Presentation.mp3'), filename: 'audio.mp3')
song7a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_04_-_Corporate_Uplifting.mp3'), filename: 'audio.mp3')
song7a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_05_-_Corporate_Software.mp3'), filename: 'audio.mp3')
song7a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_06_-_Corporate_Advertisement.mp3'), filename: 'audio.mp3')
song7a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_07_-_Corporate_Technology.mp3'), filename: 'audio.mp3')
song7a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_08_-_Corporate_Business.mp3'), filename: 'audio.mp3')
song7a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_09_-_Corporate_Vision.mp3'), filename: 'audio.mp3')
song7a10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music/Scott_Holmes_-_10_-_Inspiring_Corporate.mp3'), filename: 'audio.mp3')

album7b = Album.create(title: 'Corporate & Motivational Music 2', year: 2018, genre: "Indie Rock", artist_id: artist7.id)
album7b.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_Corporate__Motivational_Music_2_-_2018082080951088.jpg'), filename: 'cover.jpg')
song7b1 = Song.create(title: "Driven To Success", duration: 181, album_id: album7b.id)
song7b2 = Song.create(title: "Hopeful Journey", duration: 210, album_id: album7b.id)
song7b3 = Song.create(title: "Aspire", duration: 187, album_id: album7b.id)
song7b4 = Song.create(title: "Teamwork", duration: 159, album_id: album7b.id)
song7b5 = Song.create(title: "Beyond Dreams", duration: 107, album_id: album7b.id)
song7b6 = Song.create(title: "Reach for Success", duration: 116, album_id: album7b.id)
song7b7 = Song.create(title: "Think BIG", duration: 169, album_id: album7b.id)
song7b8 = Song.create(title: "Motivational", duration: 181, album_id: album7b.id)
song7b9 = Song.create(title: "We Made It", duration: 211, album_id: album7b.id)
song7b10 = Song.create(title: "Follow your Dreams", duration: 163, album_id: album7b.id)
song7b11 = Song.create(title: "Make Your Dream Reality", duration: 217, album_id: album7b.id)
song7b12 = Song.create(title: "Shine Bright", duration: 212, album_id: album7b.id)
song7b13 = Song.create(title: "Big Apple", duration: 166, album_id: album7b.id)
song7b1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_01_-_Driven_To_Success.mp3'), filename: 'audio.mp3')
song7b2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_02_-_Hopeful_Journey.mp3'), filename: 'audio.mp3')
song7b3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_03_-_Aspire.mp3'), filename: 'audio.mp3')
song7b4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_04_-_Teamwork.mp3'), filename: 'audio.mp3')
song7b5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_05_-_Beyond_Dreams.mp3'), filename: 'audio.mp3')
song7b6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_06_-_Reach_for_Success.mp3'), filename: 'audio.mp3')
song7b7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_07_-_Think_BIG.mp3'), filename: 'audio.mp3')
song7b8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_08_-_Motivational.mp3'), filename: 'audio.mp3')
song7b9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_09_-_We_Made_It.mp3'), filename: 'audio.mp3')
song7b10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_10_-_Follow_your_Dreams.mp3'), filename: 'audio.mp3')
song7b11.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_11_-_Make_Your_Dream_Reality.mp3'), filename: 'audio.mp3')
song7b12.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_12_-_Shine_Bright.mp3'), filename: 'audio.mp3')
song7b13.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Corporate__Motivational_Music_2/Scott_Holmes_-_13_-_Big_Apple.mp3'), filename: 'audio.mp3')

album7c = Album.create(title: 'Happy Music', year: 2017, genre: "Indie Rock", artist_id: artist7.id)
album7c.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_Happy_Music_-_2017090482359566.png'), filename: 'cover.jpg')
song7c1 = Song.create(title: "Our Big Adventure", duration: 164, album_id: album7c.id)
song7c2 = Song.create(title: "Ukelele Whistle", duration: 99, album_id: album7c.id)
song7c3 = Song.create(title: "So Happy", duration: 130, album_id: album7c.id)
song7c4 = Song.create(title: "Happy Ukelele", duration: 160, album_id: album7c.id)
song7c5 = Song.create(title: "Kiss the Sky", duration: 182, album_id: album7c.id)
song7c6 = Song.create(title: "Happy Days", duration: 194, album_id: album7c.id)
song7c7 = Song.create(title: "Positive and Fun", duration: 179, album_id: album7c.id)
song7c8 = Song.create(title: "Skin In My Step", duration: 107, album_id: album7c.id)
song7c9 = Song.create(title: "Happy Whistle", duration: 178, album_id: album7c.id)
song7c10 = Song.create(title: "A New Day", duration: 163, album_id: album7c.id)
song7c11 = Song.create(title: "Happy Ending", duration: 153, album_id: album7c.id)
song7c12 = Song.create(title: "Feeling Sunny", duration: 123, album_id: album7c.id)
song7c13 = Song.create(title: "Inspiring and Upbeat", duration: 131, album_id: album7c.id)
song7c14 = Song.create(title: "Bouncy Fun Song", duration: 138, album_id: album7c.id)
song7c15 = Song.create(title: "Clap Your Hands", duration: 197, album_id: album7c.id)
song7c1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_01_-_Our_Big_Adventure.mp3'), filename: 'audio.mp3')
song7c2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_02_-_Ukulele_Whistle.mp3'), filename: 'audio.mp3')
song7c3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_03_-_So_Happy.mp3'), filename: 'audio.mp3')
song7c4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_04_-_Happy_Ukulele.mp3'), filename: 'audio.mp3')
song7c5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_05_-_Kiss_the_Sky.mp3'), filename: 'audio.mp3')
song7c6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_06_-_Happy_Days.mp3'), filename: 'audio.mp3')
song7c7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_07_-_Positive_and_Fun.mp3'), filename: 'audio.mp3')
song7c8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_08_-_Skip_In_my_Step.mp3'), filename: 'audio.mp3')
song7c9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_09_-_Happy_Whistle.mp3'), filename: 'audio.mp3')
song7c10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_10_-_A_New_Day.mp3'), filename: 'audio.mp3')
song7c11.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_11_-_Happy_Ending.mp3'), filename: 'audio.mp3')
song7c12.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_12_-_Feeling_Sunny.mp3'), filename: 'audio.mp3')
song7c13.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_13_-_Inspiring_and_Upbeat.mp3'), filename: 'audio.mp3')
song7c14.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_14_-_Bouncy_Fun_Song.mp3'), filename: 'audio.mp3')
song7c15.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/Scott_Holmes_-_Happy_Music/Scott_Holmes_-_15_-_Clap_your_Hands.mp3'), filename: 'audio.mp3')

artist8 = Artist.create(name: 'State Shirt')
artist8.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist8.jpg'), filename: 'pic.jpg')
album8a = Album.create(title: 'This Is Old', year: 2010, genre: "Indie Rock", artist_id: artist8.id)
album8a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_This_Is_Old_-_20110821155111436.jpg'), filename: 'cover.jpg')
song8a1 = Song.create(title: "This Is Old", duration: 226, album_id: album8a.id)
song8a2 = Song.create(title: "Time To Go", duration: 234, album_id: album8a.id)
song8a3 = Song.create(title: "Fell Out of the Sky", duration: 300, album_id: album8a.id)
song8a4 = Song.create(title: "Computer", duration: 242, album_id: album8a.id)
song8a5 = Song.create(title: "Up Up Up Up Up", duration: 224, album_id: album8a.id)
song8a6 = Song.create(title: "I Hate California", duration: 299, album_id: album8a.id)
song8a7 = Song.create(title: "So Weird", duration: 206, album_id: album8a.id)
song8a8 = Song.create(title: "Chemma Chi", duration: 157, album_id: album8a.id)
song8a9 = Song.create(title: "Hospital Hill", duration: 290, album_id: album8a.id)
song8a10 = Song.create(title: "Conway Station Road", duration: 163, album_id: album8a.id)
song8a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_01_-_This_is_Old.mp3'), filename: 'audio.mp3')
song8a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_02_-_Time_To_Go.mp3'), filename: 'audio.mp3')
song8a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_03_-_Fell_Out_of_the_Sky.mp3'), filename: 'audio.mp3')
song8a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_04_-_Computer.mp3'), filename: 'audio.mp3')
song8a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_05_-_Up_Up_Up_Up_Up.mp3'), filename: 'audio.mp3')
song8a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_06_-_I_Hate_California.mp3'), filename: 'audio.mp3')
song8a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_07_-_So_Weird.mp3'), filename: 'audio.mp3')
song8a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_08_-_Chemma_Chi.mp3'), filename: 'audio.mp3')
song8a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_09_-_Hospital_HIll.mp3'), filename: 'audio.mp3')
song8a10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/State_Shirt_-_This_Is_Old/State_Shirt_-_10_-_Conway_Station_Road.mp3'), filename: 'audio.mp3')

artist9 = Artist.create(name: 'The Freak Fandango Orchestra')
artist9.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist9.jpg'), filename: 'pic.jpg')
album9a = Album.create(title: 'Tales Of A Dead Fish', year: 2011, genre: "Indie Rock", artist_id: artist9.id)
album9a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish_-_2012020325233354.jpg'), filename: 'cover.jpg')
song9a1 = Song.create(title: "Requiem for a Fish", duration: 220, album_id: album9a.id)
song9a2 = Song.create(title: "Late as Usual", duration: 216, album_id: album9a.id)
song9a3 = Song.create(title: "Balkan Beats", duration: 230, album_id: album9a.id)
song9a4 = Song.create(title: "No means no", duration: 257, album_id: album9a.id)
song9a5 = Song.create(title: "Hitmans Lovesong feat. Paola Graziano", duration: 296, album_id: album9a.id)
song9a6 = Song.create(title: "At the beginning", duration: 308, album_id: album9a.id)
song9a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_01_-_Requiem_for_a_Fish.mp3'), filename: 'audio.mp3')
song9a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_02_-_Late_as_Usual.mp3'), filename: 'audio.mp3')
song9a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_03_-_Balkan_Beats.mp3'), filename: 'audio.mp3')
song9a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_04_-_No_means_no.mp3'), filename: 'audio.mp3')
song9a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_05_-_Hitmans_Lovesong_feat_Paola_Graziano.mp3'), filename: 'audio.mp3')
song9a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/indie+rock/The_Freak_Fandango_Orchestra_-_Tales_Of_A_Dead_Fish/The_Freak_Fandango_Orchestra_-_06_-_At_the_beginning.mp3'), filename: 'audio.mp3')

artist10 = Artist.create(name: 'Stone Byron')
artist10.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist10.jpg'), filename: 'pic.jpg')
album10a = Album.create(title: 'Camera I, Camera II', year: 2017, genre: "Psych Rock", artist_id: artist10.id)
album10a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/Camera_I_Camera_II_-_CI_CII/Camera_I_Camera_II_-_CI_CII_-_20181013203427435.JPG'), filename: 'cover.jpg')
song10a1 = Song.create(title: "Summer Never Rolls", duration: 226, album_id: album10a.id)
song10a2 = Song.create(title: "Home/Body", duration: 156, album_id: album10a.id)
song10a3 = Song.create(title: "Stone Byron", duration: 82, album_id: album10a.id)
song10a4 = Song.create(title: "Other's Prayers", duration: 202, album_id: album10a.id)
song10a5 = Song.create(title: "Cider & Goth", duration: 184, album_id: album10a.id)
song10a6 = Song.create(title: "Far From the Ideal", duration: 222, album_id: album10a.id)
song10a7 = Song.create(title: "Language Reveals Thinking", duration: 142, album_id: album10a.id)
song10a8 = Song.create(title: "Like the Laughter of Childe", duration: 194, album_id: album10a.id)
song10a9 = Song.create(title: "Sonic Twin", duration: 182, album_id: album10a.id)
song10a10 = Song.create(title: "Neglect & Time", duration: 130, album_id: album10a.id)
song10a11 = Song.create(title: "(Y)our Blues", duration: 180, album_id: album10a.id)
song10a12 = Song.create(title: "Man Darting", duration: 166, album_id: album10a.id)
song10a13 = Song.create(title: "Camera I, Camera II", duration: 180, album_id: album10a.id)
song10a14 = Song.create(title: "The Daily Ballet", duration: 146, album_id: album10a.id)
song10a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/Camera_I_Camera_II_-_CI_CII/Camera_I_Camera_II_-_01_-_Back_to_Back.mp3'), filename: 'audio.mp3')
song10a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/Camera_I_Camera_II_-_CI_CII/Camera_I_Camera_II_-_02_-_Chaos_At_Her_Best.mp3'), filename: 'audio.mp3')
song10a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/Camera_I_Camera_II_-_CI_CII/Camera_I_Camera_II_-_03_-_Move_the_Mountains.mp3'), filename: 'audio.mp3')
song10a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_01_-_Jules_Verne_Machines_ID_1007.mp3'), filename: 'audio.mp3')
song10a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_02_-_Shadow_Man_ID_986.mp3'), filename: 'audio.mp3')
song10a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_03_-_Streetlife_-_Silentfilm_ID_981.mp3'), filename: 'audio.mp3')
song10a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_04_-_Deeply_Dungeon_ID_957.mp3'), filename: 'audio.mp3')
song10a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_06_-_Lazy_Partners_ID_1004.mp3'), filename: 'audio.mp3')
song10a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_07_-_Bees_Disco_ID_993.mp3'), filename: 'audio.mp3')
song10a10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_08_-_Bernie_the_Cop_A_ID_976.mp3'), filename: 'audio.mp3')
song10a11.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_09_-_Little_Shadows_ID_984.mp3'), filename: 'audio.mp3')
song10a12.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_10_-_Phantom_Hunters_ID_985.mp3'), filename: 'audio.mp3')
song10a13.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_11_-_Searching_for_my_Kaleidoskope_ID_992.mp3'), filename: 'audio.mp3')
song10a14.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/house/Lobo_Loco_-_Over_Midnight/Lobo_Loco_-_12_-_Searching_for_Zelda_ID_948.mp3'), filename: 'audio.mp3')

artist11 = Artist.create(name: 'KieLoBot')
artist11.photo.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/artists/artist11.jpg'), filename: 'pic.jpg')
album11a = Album.create(title: 'Hounds of Darkmoor', year: 2017, genre: "Psych Rock", artist_id: artist11.id)
album11a.cover.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_Hounds_of_Darkmoor_-_2017071090224168.jpg'), filename: 'cover.jpg')
song11a1 = Song.create(title: "Tanzen (K ID 22)", duration: 224, album_id: album11a.id)
song11a2 = Song.create(title: "Dealer (K ID 22)", duration: 199, album_id: album11a.id)
song11a3 = Song.create(title: "Freeze (K ID 22)", duration: 254, album_id: album11a.id)
song11a4 = Song.create(title: "Jeannie (K ID 22)", duration: 172, album_id: album11a.id)
song11a5 = Song.create(title: "Rosalie (K ID 22)", duration: 239, album_id: album11a.id)
song11a6 = Song.create(title: "Sandsofa (K ID 22)", duration: 368, album_id: album11a.id)
song11a7 = Song.create(title: "Seniorita (K ID 22)", duration: 254, album_id: album11a.id)
song11a8 = Song.create(title: "Alles Leer (K ID 22)", duration: 315, album_id: album11a.id)
song11a9 = Song.create(title: "Wirklich Wichtig Electromix (K ID 22)", duration: 694, album_id: album11a.id)
song11a10 = Song.create(title: "Boss (K ID 22)", duration: 140, album_id: album11a.id)
song11a11 = Song.create(title: "Hounds of Darkmoor (K ID 22)", duration: 584, album_id: album11a.id)
song11a1.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_Tanzen_K_ID_22.mp3'), filename: 'audio.mp3')
song11a2.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_04_-_Dealer_K_ID_23.mp3'), filename: 'audio.mp3')
song11a3.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_05_-_Freeze_K_ID_24.mp3'), filename: 'audio.mp3')
song11a4.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_06_-_Jeannie_K_ID_25.mp3'), filename: 'audio.mp3')
song11a5.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_07_-_Rosalie_K_ID_26.mp3'), filename: 'audio.mp3')
song11a6.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_08_-_Sandsofa_K_ID_27.mp3'), filename: 'audio.mp3')
song11a7.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_09_-_Seniorita_K_ID_28.mp3'), filename: 'audio.mp3')
song11a8.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_10_-_Alles_Leer_K_ID_29.mp3'), filename: 'audio.mp3')
song11a9.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_11_-_Boss_K_ID_30.mp3'), filename: 'audio.mp3')
song11a10.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_11_-_Wirklich_Wichtig_Electromix_ID_108.mp3'), filename: 'audio.mp3')
song11a11.audio.attach(io: EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/songs/psych+rock/KieLoBot_-_Hounds_of_Darkmoor/KieLoBot_-_12_-_Hounds_of_Darkmoor_ID_109.mp3'), filename: 'audio.mp3')




playlist1 = Playlist.create(title: '(૭ ◉༬◉)૭⁾⁾⁾⁾', description: "^_^", user_id: user1.id)
c = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/everything-everything-get-to-heaven-big.jpg')
playlist1.photo.attach(io: c, filename: 'snowball.jpg')
playlist2 = Playlist.create(title: '~ ✰ 💸 make that money 💸 ✰ ~', user_id: user2.id)
d = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/How-to-Destroy-Angels-EP-Digital-Cover-Art-600px.jpg')
playlist2.photo.attach(io: d, filename: 'snowball.jpg')
playlist3 = Playlist.create(title: 'flowers and hearts', description: "<3", user_id: user1.id )
e = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/images.jpeg')
playlist3.photo.attach(io: e, filename: 'snowball.jpg')
playlist4 = Playlist.create(title: 'chill vibes', description: "", user_id: user2.id )
f = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/hitlist.jpg')
playlist4.photo.attach(io: f, filename: 'snowball.jpg')
playlist5 = Playlist.create(title: 'study music', description: "", user_id: user2.id )
g = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/space.jpg')
playlist5.photo.attach(io: g, filename: 'snowball.jpg')
playlist6 = Playlist.create(title: '🌞 🌧🌚 🌧🌞 🌧🌝 🌧🌞', description: "", user_id: user1.id )
h = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/woman.jpg')
playlist6.photo.attach(io: h, filename: 'snowball.jpg')
playlist7 = Playlist.create(title: 'workout music', description: "", user_id: user1.id )
i = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/zebra.jpg')
playlist7.photo.attach(io: i, filename: 'snowball.jpg')
playlist8 = Playlist.create(title: 'googled it', description: "", user_id: user1.id )
j = EzDownload.open('https://s3-us-west-1.amazonaws.com/clone-ify-public/playlists/collage.jpg')
playlist8.photo.attach(io: j, filename: 'snowball.jpg')

pS1 = PlaylistSong.create(playlist_id: playlist1.id,song_id: song2a2.id)
pS2 = PlaylistSong.create(playlist_id: playlist3.id,song_id: song1a5.id)
pS2 = PlaylistSong.create(playlist_id: playlist1.id,song_id: song2a13.id)
pS3 = PlaylistSong.create(playlist_id: playlist2.id,song_id: song2a1.id)
pS4 = PlaylistSong.create(playlist_id: playlist1.id,song_id: song2a3.id)
pS5 = PlaylistSong.create(playlist_id: playlist2.id,song_id: song2a10.id)
pS6 = PlaylistSong.create(playlist_id: playlist2.id,song_id: song1a1.id)
pS7 = PlaylistSong.create(playlist_id: playlist1.id,song_id: song2a11.id)
pS8 = PlaylistSong.create(playlist_id: playlist3.id,song_id: song1a6.id)
pS9 = PlaylistSong.create(playlist_id: playlist2.id,song_id: song2a12.id)
pS10 = PlaylistSong.create(playlist_id: playlist4.id,song_id: song2a7.id)
pS11 = PlaylistSong.create(playlist_id: playlist5.id,song_id: song11a2.id)
pS12 = PlaylistSong.create(playlist_id: playlist6.id,song_id: song10a5.id)
pS12 = PlaylistSong.create(playlist_id: playlist7.id,song_id: song6b13.id)
pS13 = PlaylistSong.create(playlist_id: playlist8.id,song_id: song7b1.id)
pS14 = PlaylistSong.create(playlist_id: playlist4.id,song_id: song7c3.id)
pS15 = PlaylistSong.create(playlist_id: playlist5.id,song_id: song8a10.id)
pS16 = PlaylistSong.create(playlist_id: playlist6.id,song_id: song9a1.id)
pS17 = PlaylistSong.create(playlist_id: playlist7.id,song_id: song2a11.id)
pS18 = PlaylistSong.create(playlist_id: playlist8.id,song_id: song4a5.id)
pS19 = PlaylistSong.create(playlist_id: playlist4.id,song_id: song11a11.id)
pS20 = PlaylistSong.create(playlist_id: playlist5.id,song_id: song6a7.id)
pS21 = PlaylistSong.create(playlist_id: playlist6.id,song_id: song7a2.id)
pS22 = PlaylistSong.create(playlist_id: playlist7.id,song_id: song7b5.id)
pS22 = PlaylistSong.create(playlist_id: playlist8.id,song_id: song2a13.id)
pS23 = PlaylistSong.create(playlist_id: playlist4.id,song_id: song8a1.id)
pS24 = PlaylistSong.create(playlist_id: playlist5.id,song_id: song9a3.id)
pS25 = PlaylistSong.create(playlist_id: playlist6.id,song_id: song2a10.id)
pS26 = PlaylistSong.create(playlist_id: playlist7.id,song_id: song10a1.id)
pS27 = PlaylistSong.create(playlist_id: playlist8.id,song_id: song2a11.id)
pS28 = PlaylistSong.create(playlist_id: playlist1.id,song_id: song11a6.id)
pS29 = PlaylistSong.create(playlist_id: playlist2.id,song_id: song11a10.id)
pS30 = PlaylistSong.create(playlist_id: playlist3.id,song_id: song10a7.id)
pS31 = PlaylistSong.create(playlist_id: playlist4.id,song_id: song2a2.id)
pS32 = PlaylistSong.create(playlist_id: playlist5.id,song_id: song1a5.id)
pS32 = PlaylistSong.create(playlist_id: playlist6.id,song_id: song2a13.id)
pS33 = PlaylistSong.create(playlist_id: playlist7.id,song_id: song2a1.id)
pS34 = PlaylistSong.create(playlist_id: playlist8.id,song_id: song2a3.id)
pS35 = PlaylistSong.create(playlist_id: playlist4.id,song_id: song2a10.id)
pS36 = PlaylistSong.create(playlist_id: playlist5.id,song_id: song1a1.id)
pS37 = PlaylistSong.create(playlist_id: playlist6.id,song_id: song2a11.id)
pS38 = PlaylistSong.create(playlist_id: playlist7.id,song_id: song1a6.id)
pS39 = PlaylistSong.create(playlist_id: playlist8.id,song_id: song2a12.id)
pS40 = PlaylistSong.create(playlist_id: playlist1.id,song_id: song5a7.id)
